on:
  workflow_dispatch:

jobs:
  apply-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository collaborators
        id: get-collaborators
        run: |
          COLLABORATORS=$(gh api repos/${{ github.repository }}/collaborators --jq '.[].login')
          echo "COLLABORATORS=$COLLABORATORS" >> $GITHUB_ENV
          COLLABORATOR_COUNT=$(echo "$COLLABORATORS" | wc -w)
          echo "COLLABORATOR_COUNT=$COLLABORATOR_COUNT" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Define branch protection rules for development
        id: define-rules-development
        run: |
          echo "Defining branch protection rules for development"
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "required_pull_request_reviews": {
                "required_approving_review_count": '"$COLLABORATOR_COUNT"',
                "require_code_owner_reviews": false
              },
              "enforce_admins": true
            }' \
            https://api.github.com/repos/${{ github.repository }}/branches/development/protection

      - name: Define branch protection rules for staging
        id: define-rules-staging
        run: |
          echo "Defining branch protection rules for staging"
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "required_pull_request_reviews": {
                "required_approving_review_count": '"$COLLABORATOR_COUNT"',
                "require_code_owner_reviews": false
              },
              "enforce_admins": true
            }' \
            https://api.github.com/repos/${{ github.repository }}/branches/staging/protection

      - name: Define branch protection rules for production
        id: define-rules-production
        run: |
          echo "Defining branch protection rules for production"
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "required_pull_request_reviews": {
                "required_approving_review_count": '"$COLLABORATOR_COUNT"',
                "require_code_owner_reviews": true
              },
              "enforce_admins": true
            }' \
            https://api.github.com/repos/${{ github.repository }}/branches/production/protection